### ISSUE TITLE
I got a Italy Green Pass, it is verified from the German official App CovPass, but it is denied from VerificC19

### ISSUE THREAD

**Issue by yzhang666** [ministero-salute/it-dgc-verificac19-sdk-android#147]
# Issue content
I have an Italy Green Pass, and I decode the QR code, check the UVCI from https://get.dgc.gov.it/v1/dgc/settings; it is not on the blacklist. Then, I digest the UVCI, and check the records from https://get.dgc.gov.it/v1/dgc/drl, it is not on the list either,

The owner had the booster dose (all of the doses are Spikevax and Vaxzevria), but unfortunately, he got sick a few days ago. The trick thing is, from the German official App CovPass, if you use the app to scan the code, it is verified with green; but if to use the Italian VerificC19, it shows the gree pass is denied with red. 

My question is, besides the above two blacklists, does the Italian app use any additional methods (or codes) to check the validity of a QR code?

**Comment by rawmain** [comment]
Hello @yzhang666 

> My question is, besides the above two blacklists, does the Italian app use any additional methods (or codes) to check the validity of a QR code?

Verifier-apps of other countries use different validation rules/settings for internal scenarios checks. 

VerificaC19 apps for iOS/Android, this official DGC-SDK Android/Kotlin and [approved 3rd-party SDK/Libs](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding) rely indeed on the Italian rules+parameters : 

- Medicinal + IT / NOT_IT issue rules for DGC validity start/end = check [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings)

- Specific Scanmode parameters = check [scanmode documentation](https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md)

- UVCI checks vs blacklist in Validation Rules + [DRL](https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md)

If you're getting KO output for such certificate, regardless of the selected scanmode, check with debug variant and/or inspect logcat in order to read the detailed status/reason of the KO.

**Comment by yzhang666** [comment]
> Hello @yzhang666
> 
> > My question is, besides the above two blacklists, does the Italian app use any additional methods (or codes) to check the validity of a QR code?
> 
> Verifier-apps of other countries use different validation rules/settings for internal scenarios checks.
> 
> VerificaC19 apps for iOS/Android, this official DGC-SDK Android/Kotlin and [approved 3rd-party SDK/Libs](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding) rely indeed on the Italian rules+parameters :
> 
> * Medicinal + IT / NOT_IT issue rules for DGC validity start/end = check [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings)
> * Specific Scanmode parameters = check [scanmode documentation](https://github.com/ministero-salute/it-dgc-documentation/blob/master/SCANMODE.md)
> * UVCI checks vs blacklist in Validation Rules + [DRL](https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md)
> 
> If you're getting KO output for such certificate, regardless of the selected scanmode, check with debug variant and/or inspect logcat in order to read the detailed status/reason of the KO.

Hi, thx for your reply. I confirmed that the green pass's UVCI is neither on the blacklist nor on the DRL, and I will check the [Validation Rules](https://get.dgc.gov.it/v1/dgc/settings) again carefully. Many thanks.
