### ISSUE TITLE
Xamarin support?

### ISSUE THREAD

**Issue by energywave** [ministero-salute/it-dgc-verificac19-sdk-android#32]
**Is your feature request related to a problem? Please describe.**
E' previsto l'utilizzo dell'SDK da Xamarin / Xamarin Forms?

**Describe the solution you'd like**
Sarebbe gradito un esempio di utilizzo collaudato e funzionante da poter utilizzare in ambiente Xamarin / Xamarin Forms.

**Describe alternatives you've considered**
Nessuna alternativa. Il nostro sistema è sviluppato in Xamarin Forms, non si può pensare di riscrivere l'applicazione...

**Comment by acaliaro** [comment]
Ciao @energywave . Credo che l'unica possibilità sia quella di generare la libreria e poi fare il solito binding di Xamarin, come descritto [https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/](url)

**Comment by energywave** [comment]
> Credo che l'unica possibilità sia quella di generare la libreria e poi fare il solito binding di Xamarin

Ciao Alessandro, ti ringrazio. Speravo potesse esserci un supporto ufficiale... Certo quella da te indicata è l'unica via in caso di indisponibilità. Non avendolo mai ancora fatto già vedo una perdita di tempo immane però... :(

**Comment by acaliaro** [comment]
Credo che il supporto ufficiale non venga considerato, visto l'andazzo di questo progetto

**Comment by energywave** [comment]
Eh, mi sa tanto anche a me. Peraltro sembra già un problema riuscire a compilarlo, vedendo l'altro tuo issue... Chissà che bello importarlo in Xamarin. Vabbè, ci proverò. Intanto grazie :)

**Comment by vlajkoe** [comment]
Hi, 
has anyone successfully created anything usable for Xamarin?
The documentation "ministerio-salute" provided is not usable for creating anything... :/

**Comment by rawmain** [comment]
Hello @vlajkoe 

> Hi, has anyone successfully created anything usable for Xamarin? The documentation "ministerio-salute" provided is not usable for creating anything... :/

The Italian Ministry of Health has also validated some third-party SDK/libraries - _not only this Android/Kotlin SDK_ - in order to allow developers to deploy desktop/mobile/web apps for production environments & in compliance with [DPCM 12/10/2021 - paragraphs 12 & 13](https://www.governo.it/sites/governo.it/files/DPCM_12_ottobre.pdf).

If you check the[ official SDK Onboarding repository](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding#lista-librerie) you'll see indeed that there is also a .NET library available.
