### ISSUE TITLE
Access Denied to get.dgc.gov.it and testaka4.sogei.it

### ISSUE THREAD

**Issue by dokaha** [ministero-salute/it-dgc-verificac19-sdk-android#86]
Hello,

i built my own app using the VerificaC19-SDK, but the app is not able to download the DGC - not from test and also not from productive server. On the Terminal from my device is see this error popping up periodically:
```
You don't have permission to access "https://testaka4.sogei.it/v1/dgc/settings" on this server.
```

Also with internet browsers like firefox or chrome i get these message:
You don't have permission to access "http://testaka4.sogei.it/" on this server.
You don't have permission to access "http://get.dgc.gov.it/v1/dgc/" on this server.

What may be the problem, and how to analyze it?
My Internet Exit Point is outside italy, but still in EU - is this maybe a problem?

thanks for helping me!

**Comment by bobbysimon24** [comment]
Hi @dokaha,
I think you're trying to access the "debug" values of the app, but those links are accessible only for some developers. You must use the "release" values, you can do in the build.gradle file of the dgc-sdk module, here you can see 2 buildTypes:
```
buildTypes {
        debug {
            minifyEnabled false
            buildConfigField "String", "BASE_URL", "\"https://testaka4.sogei.it/v1/dgc/\""
            buildConfigField "String", "SERVER_HOST", "\"testaka4.sogei.it\""
            buildConfigField "String", "CERTIFICATE_SHA", "\"sha256/R0d+cI8vTcJ3sCbpfQCH0OmdBbulPH3deYhngzOqJVA=\""
            buildConfigField "String", "SDK_VERSION", "\"1.0.4\""
        }

        release {
            buildConfigField "String", "BASE_URL", "\"https://get.dgc.gov.it/v1/dgc/\""
            buildConfigField "String", "SERVER_HOST", "\"get.dgc.gov.it\""
            buildConfigField "String", "CERTIFICATE_SHA", "\"sha256/7cZJIDPacG8FS3pq6Mvxg+7yBDM/VYc2alOcbVe/e74=\""
            buildConfigField "String", "SDK_VERSION", "\"1.0.4\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

```
As you can see, the debug values are different from the release values, so you can copy and paste the release values in the debug values and you will able to connect in debug mode too.
Otherwise you can compile the app in release variant to get around the problem, you can do it in **Build**->**Select Build Variant**
